export type StageType = "on-stage" | "off-stage";

export type EventCategory =
  | "Music"
  | "Musical Instruments"
  | "Dance"
  | "Theatre"
  | "Literary & Oratory"
  | "Fine Arts & Visual Arts";

export interface FestivalEvent {
  id: string;
  name: string;
  stageType: StageType;
  category: EventCategory;
  type: "solo" | "group";
  gender?: "male" | "female" | "combined" | "open";
  duration?: string;
  participantsCount?: string | number;
  accompanistsCount?: string | number;
  settingTime?: string;
  guidelines: string[];
}

export const DEPARTMENTS = [
  { code: "CSE", name: "Computer Science & Engineering" },
  { code: "EC1", name: "Electronics & Communication Engineering 1" },
  { code: "EC2", name: "Electronics & Communication Engineering 2" },
  { code: "EEE", name: "Electrical & Electronics Engineering" },
  { code: "ME", name: "Mechanical Engineering" },
  { code: "CEE", name: "Civil Engineering" },
];

export const FESTIVAL_EVENTS: FestivalEvent[] = [
  {
    id: "light-music",
    name: "Light Music",
    stageType: "on-stage",
    category: "Music",
    type: "solo",
    gender: "open",
    duration: "5 minutes",
    participantsCount: 1,
    accompanistsCount: 2,
    guidelines: [
      "Duration – 5 minutes",
      "Separate for Male and Female",
      "2 accompanists are allowed",
    ],
  },
  {
    id: "classical-music",
    name: "Classical Music",
    stageType: "on-stage",
    category: "Music",
    type: "solo",
    gender: "open",
    duration: "10 minutes",
    participantsCount: 1,
    accompanistsCount: 2,
    guidelines: [
      "Duration – 10 minutes",
      "Separate for Male and Female",
      "It can be either Hindustani or Carnatic Music",
      "2 accompanists are allowed",
    ],
  },
  {
    id: "mappilappattu-group",
    name: "Mappilappattu (Group)",
    stageType: "on-stage",
    category: "Music",
    type: "group",
    gender: "combined",
    duration: "10 minutes",
    participantsCount: 6,
    guidelines: [
      "Duration – 10 minutes",
      "Participants: 6 (Male and Female combined)",
    ],
  },
  {
    id: "mappilappattu-solo",
    name: "Mappilappattu (Solo)",
    stageType: "on-stage",
    category: "Music",
    type: "solo",
    gender: "open",
    duration: "5 minutes",
    participantsCount: 1,
    guidelines: [
      "Duration – 5 minutes",
      "Separate for Male and Female",
    ],
  },
  {
    id: "group-song-indian",
    name: "Group Song (Indian)",
    stageType: "on-stage",
    category: "Music",
    type: "group",
    gender: "combined",
    duration: "10 minutes",
    participantsCount: 6,
    accompanistsCount: 3,
    guidelines: [
      "Duration – 10 minutes",
      "Participants – 6",
      "Accompanists – 3",
      "Instruments to be played by the participants only",
    ],
  },
  {
    id: "group-song-western",
    name: "Group Song (Western)",
    stageType: "on-stage",
    category: "Music",
    type: "group",
    gender: "combined",
    duration: "10 minutes",
    participantsCount: 6,
    accompanistsCount: 3,
    guidelines: [
      "Duration – 10 minutes",
      "Participants – 6",
      "Accompanists – 3",
      "Instruments to be played by the participants only",
    ],
  },
  {
    id: "vocal-western-solo",
    name: "Vocal Western (Solo)",
    stageType: "on-stage",
    category: "Music",
    type: "solo",
    gender: "open",
    duration: "4-6 minutes",
    participantsCount: 1,
    accompanistsCount: 2,
    guidelines: [
      "Duration – 4-6 minutes",
      "Separate for Male and Female",
      "Accompanists – 2",
    ],
  },
  {
    id: "folk-song",
    name: "Folk Song",
    stageType: "on-stage",
    category: "Music",
    type: "group",
    gender: "combined",
    duration: "8-10 minutes",
    participantsCount: 9,
    guidelines: [
      "Duration – 8-10 minutes",
      "Participants – 9 (Male and Female combined)",
    ],
  },
  {
    id: "semiclassical-song",
    name: "Semiclassical Song",
    stageType: "on-stage",
    category: "Music",
    type: "solo",
    gender: "open",
    duration: "8-10 minutes",
    participantsCount: 1,
    accompanistsCount: 2,
    guidelines: [
      "Duration – 8-10 minutes",
      "Separate for Male and Female",
      "Accompanists – 2",
      "It can be either Hindustani or Carnatic Music",
    ],
  },
  {
    id: "patriotic-song-malayalam",
    name: "Patriotic Song (Malayalam)",
    stageType: "on-stage",
    category: "Music",
    type: "group",
    gender: "combined",
    duration: "5 minutes",
    participantsCount: 7,
    guidelines: [
      "Duration – 5 minutes",
      "Participants – 7",
    ],
  },
  {
    id: "vanchipattu-group",
    name: "Vanchipattu (Group)",
    stageType: "on-stage",
    category: "Music",
    type: "group",
    gender: "combined",
    duration: "10 minutes",
    participantsCount: 10,
    guidelines: [
      "Duration – 10 minutes",
      "Participants – 10",
    ],
  },
  {
    id: "kathakali-sangeetham-solo",
    name: "Kathakali Sangeetham (Solo)",
    stageType: "on-stage",
    category: "Music",
    type: "solo",
    gender: "open",
    duration: "10 minutes",
    participantsCount: 1,
    guidelines: [
      "Duration – 10 minutes",
      "Separate for Male and Female",
    ],
  },
  {
    id: "ganamela",
    name: "Ganamela",
    stageType: "on-stage",
    category: "Music",
    type: "group",
    gender: "combined",
    duration: "10 minutes",
    participantsCount: 3,
    accompanistsCount: 4,
    settingTime: "7 minutes",
    guidelines: [
      "Duration – 10 minutes",
      "Participants – 3",
      "Accompanists – 4",
      "The instruments should be played by the participants themselves",
      "Setting Time – 7 minutes",
    ],
  },
  {
    id: "recitation-solo",
    name: "Recitation (Solo)",
    stageType: "on-stage",
    category: "Music",
    type: "solo",
    gender: "open",
    duration: "5 minutes",
    participantsCount: 1,
    accompanistsCount: 1,
    guidelines: [
      "Languages: Malayalam, English, Hindi, Arabic, Urdu, Sanskrit, Tamil",
      "Duration – 5 minutes",
      "Accompanists – 1",
    ],
  },
  {
    id: "gazal-solo",
    name: "Gazal (Solo)",
    stageType: "on-stage",
    category: "Music",
    type: "solo",
    gender: "open",
    duration: "10 minutes",
    participantsCount: 1,
    accompanistsCount: 2,
    guidelines: [
      "Duration – 10 minutes",
      "Accompanists – 2 (Harmonium and Tabla)",
      "Filmy Gazals are not allowed",
    ],
  },
  {
    id: "percussion-classical-solo",
    name: "Percussion Instruments (Classical) - Solo",
    stageType: "on-stage",
    category: "Musical Instruments",
    type: "solo",
    gender: "open",
    duration: "10 minutes",
    participantsCount: 1,
    settingTime: "5 minutes",
    guidelines: [
      "Duration – 10 minutes",
      "Setting Time – 5 minutes",
      "Category: (i) Chenda/Idayka/Maddhalam, (ii) Tabala/Pakwaz(Panchavadhyam), (iii) Mridangam/Khanjira/Ghatam/Thavil",
    ],
  },
  {
    id: "percussion-western-solo",
    name: "Percussion Instruments (Western) - Solo",
    stageType: "on-stage",
    category: "Musical Instruments",
    type: "solo",
    gender: "open",
    duration: "10 minutes",
    participantsCount: 1,
    settingTime: "5 minutes",
    guidelines: [
      "Duration – 10 minutes",
      "Setting Time – 5 minutes",
      "Category: (i) Triple Drum, (ii) Jazz",
    ],
  },
  {
    id: "stringed-classical-solo",
    name: "Stringed Instruments (Classical) - Solo",
    stageType: "on-stage",
    category: "Musical Instruments",
    type: "solo",
    gender: "open",
    duration: "10 minutes",
    participantsCount: 1,
    settingTime: "5 minutes",
    guidelines: [
      "Duration – 10 minutes",
      "Setting Time – 5 minutes",
      "Category: Violin / Veena",
    ],
  },
  {
    id: "stringed-western-solo",
    name: "Stringed Instruments (Western) - Solo",
    stageType: "on-stage",
    category: "Musical Instruments",
    type: "solo",
    gender: "open",
    duration: "10 minutes",
    participantsCount: 1,
    settingTime: "5 minutes",
    guidelines: [
      "Duration – 10 minutes",
      "Setting Time – 5 minutes",
      "Category: Violin / Guitar / Banjo / Mandoline",
    ],
  },
  {
    id: "wind-classical-solo",
    name: "Wind Instruments (Classical) - Solo",
    stageType: "on-stage",
    category: "Musical Instruments",
    type: "solo",
    gender: "open",
    duration: "10 minutes",
    participantsCount: 1,
    settingTime: "5 minutes",
    guidelines: [
      "Duration – 10 minutes",
      "Setting Time – 5 minutes",
      "Category: Flute / Bansuri / Nadaswaram / Harmonium",
    ],
  },
  {
    id: "wind-western-solo",
    name: "Wind Instruments (Western) - Solo",
    stageType: "on-stage",
    category: "Musical Instruments",
    type: "solo",
    gender: "open",
    duration: "10 minutes",
    participantsCount: 1,
    settingTime: "5 minutes",
    guidelines: [
      "Duration – 10 minutes",
      "Setting Time – 5 minutes",
      "Category: Accordion / Clarinet / Saxophone",
    ],
  },
  {
    id: "keyboard-western-solo",
    name: "Keyboard (Western) - Solo",
    stageType: "on-stage",
    category: "Musical Instruments",
    type: "solo",
    gender: "open",
    duration: "10 minutes",
    participantsCount: 1,
    settingTime: "5 minutes",
    guidelines: [
      "Duration – 10 minutes",
      "Setting Time – 5 minutes",
    ],
  },
  {
    id: "chendamelam-group",
    name: "Chendamelam (Group)",
    stageType: "on-stage",
    category: "Musical Instruments",
    type: "group",
    gender: "combined",
    duration: "10 minutes",
    participantsCount: "3-7",
    settingTime: "5 minutes",
    guidelines: [
      "Duration – 10 minutes",
      "Participants – 3-7",
      "Setting Time – 5 minutes",
    ],
  },
  {
    id: "panchavadyam-group",
    name: "Panchavadyam (Group)",
    stageType: "on-stage",
    category: "Musical Instruments",
    type: "group",
    gender: "combined",
    duration: "20 minutes",
    participantsCount: 7,
    settingTime: "5 minutes",
    guidelines: [
      "Duration – 20 minutes",
      "Participants – 7",
      "Setting Time – 5 minutes",
    ],
  },
  {
    id: "bandmelam-group",
    name: "Bandmelam (Group)",
    stageType: "on-stage",
    category: "Musical Instruments",
    type: "group",
    gender: "combined",
    duration: "20 minutes",
    participantsCount: 12,
    settingTime: "5 minutes",
    guidelines: [
      "Duration – 20 minutes",
      "Participants – 12",
      "Setting Time – 5 minutes",
    ],
  },
  {
    id: "chenda-thayambaka",
    name: "Chenda Thayambaka",
    stageType: "on-stage",
    category: "Musical Instruments",
    type: "solo",
    gender: "open",
    duration: "10 minutes",
    participantsCount: 1,
    accompanistsCount: 4,
    settingTime: "5 minutes",
    guidelines: [
      "Duration – 10 minutes",
      "Participant – 1",
      "Accompanists – 4",
      "Setting Time – 5 minutes",
    ],
  },
  {
    id: "maddhalam",
    name: "Maddhalam",
    stageType: "on-stage",
    category: "Musical Instruments",
    type: "solo",
    gender: "open",
    duration: "10 minutes",
    participantsCount: 1,
    accompanistsCount: 4,
    settingTime: "5 minutes",
    guidelines: [
      "Duration – 10 minutes",
      "Participant – 1",
      "Accompanists – 4",
      "Setting Time – 5 minutes",
    ],
  },
  {
    id: "kathakali-solo",
    name: "Kathakali (Solo)",
    stageType: "on-stage",
    category: "Dance",
    type: "solo",
    gender: "open",
    duration: "15 minutes",
    participantsCount: 1,
    guidelines: [
      "Duration – 15 minutes",
      "Separate for Male and Female",
    ],
  },
  {
    id: "kathakali-group",
    name: "Kathakali (Group)",
    stageType: "on-stage",
    category: "Dance",
    type: "group",
    gender: "combined",
    duration: "30 minutes",
    participantsCount: "Min 2",
    guidelines: [
      "Duration – 30 minutes",
      "Participants – Minimum 2",
    ],
  },
  {
    id: "bharatanatyam-solo",
    name: "Bharatanatyam (Solo)",
    stageType: "on-stage",
    category: "Dance",
    type: "solo",
    gender: "open",
    duration: "15 minutes",
    participantsCount: 1,
    accompanistsCount: 3,
    guidelines: [
      "Duration – 15 minutes",
      "Accompanists – 3",
    ],
  },
  {
    id: "mohiniyattom-solo",
    name: "Mohiniyattom (Solo)",
    stageType: "on-stage",
    category: "Dance",
    type: "solo",
    gender: "female",
    duration: "15 minutes",
    participantsCount: 1,
    accompanistsCount: 3,
    guidelines: [
      "Duration – 15 minutes",
      "Accompanists – 3",
    ],
  },
  {
    id: "classical-dance-solo",
    name: "Classical Dance (Solo)",
    stageType: "on-stage",
    category: "Dance",
    type: "solo",
    gender: "open",
    duration: "15 minutes",
    participantsCount: 1,
    accompanistsCount: 3,
    guidelines: [
      "Duration – 15 minutes",
      "Accompanists – 3",
      "Category: Kuchipudi / Odissi / Kathak / Manipuri",
    ],
  },
  {
    id: "keralanadanam-solo",
    name: "Keralanadanam (Solo)",
    stageType: "on-stage",
    category: "Dance",
    type: "solo",
    gender: "open",
    duration: "15 minutes",
    participantsCount: 1,
    accompanistsCount: 3,
    guidelines: [
      "Duration – 15 minutes",
      "Accompanists – 3",
    ],
  },
  {
    id: "folk-dance-solo",
    name: "Folk Dance (Solo)",
    stageType: "on-stage",
    category: "Dance",
    type: "solo",
    gender: "open",
    duration: "10 minutes",
    participantsCount: 1,
    accompanistsCount: 3,
    guidelines: [
      "Duration – 10 minutes",
      "Accompanists – 3",
      "Separate for Male and Female",
    ],
  },
  {
    id: "thullal-solo",
    name: "Thullal (Solo)",
    stageType: "on-stage",
    category: "Dance",
    type: "solo",
    gender: "open",
    duration: "10 minutes",
    participantsCount: 1,
    accompanistsCount: 2,
    guidelines: [
      "Duration – 10 minutes",
      "Accompanists – 2",
      "Category: Ottanthullal / Parayanthullal / Sheethankanthullal",
    ],
  },
  {
    id: "koodiyattom",
    name: "Koodiyattom",
    stageType: "on-stage",
    category: "Dance",
    type: "group",
    gender: "combined",
    duration: "30 minutes",
    participantsCount: 7,
    settingTime: "5 minutes",
    guidelines: [
      "Duration – 30 minutes",
      "Participants – 7",
      "Setting Time – 5 minutes",
    ],
  },
  {
    id: "chakyarkoothu-male",
    name: "Chakyarkoothu (Male)",
    stageType: "on-stage",
    category: "Dance",
    type: "solo",
    gender: "male",
    duration: "20 minutes",
    participantsCount: 1,
    accompanistsCount: 1,
    settingTime: "5 minutes",
    guidelines: [
      "Duration – 20 minutes",
      "Participant – 1",
      "Accompanists – 1",
      "Setting Time – 5 minutes",
    ],
  },
  {
    id: "nangyarkoothu-female",
    name: "Nangyarkoothu (Female)",
    stageType: "on-stage",
    category: "Dance",
    type: "solo",
    gender: "female",
    duration: "20 minutes",
    participantsCount: 1,
    accompanistsCount: 1,
    settingTime: "5 minutes",
    guidelines: [
      "Duration – 20 minutes",
      "Participant – 1",
      "Accompanists – 1",
      "Setting Time – 5 minutes",
    ],
  },
  {
    id: "folk-dance-group",
    name: "Folk Dance (Group)",
    stageType: "on-stage",
    category: "Dance",
    type: "group",
    gender: "open",
    duration: "10 minutes",
    participantsCount: 8,
    accompanistsCount: 5,
    guidelines: [
      "Duration – 10 minutes",
      "Participants – 8",
      "Accompanists – 5",
      "Separate for Male and Female",
    ],
  },
  {
    id: "thiruvathirakali-female",
    name: "Thiruvathirakali (Female)",
    stageType: "on-stage",
    category: "Dance",
    type: "group",
    gender: "female",
    duration: "10 minutes",
    participantsCount: 10,
    guidelines: [
      "Duration – 10 minutes",
      "Participants – 10",
      "Traditional form of Thiruvathirakali not any other form of Kaikottikali",
    ],
  },
  {
    id: "oppana-female",
    name: "Oppana (Female)",
    stageType: "on-stage",
    category: "Dance",
    type: "group",
    gender: "female",
    duration: "10 minutes",
    participantsCount: 10,
    guidelines: [
      "Duration – 10 minutes",
      "Participants – 10",
    ],
  },
  {
    id: "margamkali-female",
    name: "Margamkali (Female)",
    stageType: "on-stage",
    category: "Dance",
    type: "group",
    gender: "female",
    duration: "10 minutes",
    participantsCount: 7,
    guidelines: [
      "Duration – 10 minutes",
      "Participants – 7",
    ],
  },
  {
    id: "kolkali-male",
    name: "Kolkali (Male)",
    stageType: "on-stage",
    category: "Dance",
    type: "group",
    gender: "male",
    duration: "10 minutes",
    participantsCount: 12,
    guidelines: [
      "Duration – 10 minutes",
      "Participants – 12",
      "Traditional folk art Kolkali not Kolattam",
    ],
  },
  {
    id: "duffmutte-male",
    name: "Duffmutte (Male)",
    stageType: "on-stage",
    category: "Dance",
    type: "group",
    gender: "male",
    duration: "10 minutes",
    participantsCount: 10,
    guidelines: [
      "Duration – 10 minutes",
      "Participants – 10",
    ],
  },
  {
    id: "parichamutte-male",
    name: "Parichamutte (Male)",
    stageType: "on-stage",
    category: "Dance",
    type: "group",
    gender: "male",
    duration: "10 minutes",
    participantsCount: 8,
    guidelines: [
      "Duration – 10 minutes",
      "Participants – 8",
    ],
  },
  {
    id: "poorakali-male",
    name: "Poorakali (Male)",
    stageType: "on-stage",
    category: "Dance",
    type: "group",
    gender: "male",
    duration: "10 minutes",
    participantsCount: 12,
    guidelines: [
      "Duration – 10 minutes",
      "Participants – 12",
    ],
  },
  {
    id: "arbanamutte-male",
    name: "Arbanamutte (Male)",
    stageType: "on-stage",
    category: "Dance",
    type: "group",
    gender: "male",
    duration: "10 minutes",
    participantsCount: 10,
    guidelines: [
      "Duration – 10 minutes",
      "Participants – 10",
    ],
  },
  {
    id: "vattapatte-male",
    name: "Vattapatte (Male)",
    stageType: "on-stage",
    category: "Dance",
    type: "group",
    gender: "male",
    duration: "10 minutes",
    participantsCount: 10,
    guidelines: [
      "Duration – 10 minutes",
      "Participants – 10",
    ],
  },
  {
    id: "step-n-synchro",
    name: "Step N Synchro",
    stageType: "on-stage",
    category: "Dance",
    type: "group",
    gender: "open",
    duration: "5 minutes",
    participantsCount: 2,
    guidelines: [
      "Duration – 5 minutes",
      "Participants – 2",
      "Pairs can be same gender or different genders",
    ],
  },
  {
    id: "theme-dance",
    name: "Theme Dance",
    stageType: "on-stage",
    category: "Dance",
    type: "group",
    gender: "combined",
    duration: "10 minutes",
    participantsCount: 10,
    guidelines: [
      "Duration – 10 minutes",
      "Participants – 10",
      "Theme will be provided prior",
    ],
  },
  {
    id: "nostalgia",
    name: "Nostalgia",
    stageType: "on-stage",
    category: "Dance",
    type: "group",
    gender: "combined",
    duration: "10 minutes",
    participantsCount: 10,
    guidelines: [
      "Duration – 10 minutes",
      "Participants – 10",
      "Songs must be that of before 1980",
      "Remix are not allowed",
      "Meant for Final years",
    ],
  },
  {
    id: "spot-dance",
    name: "Spot Dance",
    stageType: "on-stage",
    category: "Dance",
    type: "solo",
    gender: "open",
    duration: "10 minutes",
    participantsCount: 1,
    guidelines: [
      "Duration – 10 minutes",
      "Participant – 1",
      "Songs will be played on the spot",
    ],
  },
  {
    id: "western-dance",
    name: "Western Dance",
    stageType: "on-stage",
    category: "Dance",
    type: "group",
    gender: "combined",
    duration: "10 minutes",
    participantsCount: "8-10",
    guidelines: [
      "Duration – 10 minutes",
      "Participants – 8-10",
    ],
  },
  {
    id: "fashion-show",
    name: "Fashion Show",
    stageType: "on-stage",
    category: "Dance",
    type: "group",
    gender: "combined",
    duration: "15 minutes",
    participantsCount: 10,
    guidelines: [
      "Duration – 15 minutes",
      "Participants – 10",
      "Theme will be provided prior",
    ],
  },
  {
    id: "drama",
    name: "Drama (English / Malayalam)",
    stageType: "on-stage",
    category: "Theatre",
    type: "group",
    gender: "combined",
    duration: "30 minutes",
    participantsCount: 7,
    accompanistsCount: 3,
    settingTime: "10 minutes",
    guidelines: [
      "Duration – 30 minutes",
      "Participants – 7",
      "Accompanists – 3",
      "Setting Time – 10 minutes",
      "Language: English or Malayalam",
    ],
  },
  {
    id: "skit",
    name: "Skit (English / Malayalam)",
    stageType: "on-stage",
    category: "Theatre",
    type: "group",
    gender: "combined",
    duration: "8-10 minutes",
    participantsCount: 6,
    accompanistsCount: 3,
    guidelines: [
      "Duration – 8-10 minutes",
      "Participants – 6",
      "Accompanists – 3",
      "Language: English or Malayalam",
    ],
  },
  {
    id: "mime",
    name: "Mime",
    stageType: "on-stage",
    category: "Theatre",
    type: "group",
    gender: "combined",
    duration: "5 minutes",
    participantsCount: 6,
    guidelines: [
      "Duration – 5 minutes",
      "Participants – 6",
    ],
  },
  {
    id: "kadhaprasangam",
    name: "Kadhaprasangam",
    stageType: "on-stage",
    category: "Theatre",
    type: "solo",
    gender: "open",
    duration: "15 minutes",
    participantsCount: 1,
    accompanistsCount: 3,
    guidelines: [
      "Duration – 15 minutes",
      "Participant – 1",
      "Accompanists – 3",
    ],
  },
  {
    id: "monoact",
    name: "Monoact",
    stageType: "on-stage",
    category: "Theatre",
    type: "solo",
    gender: "open",
    duration: "5 minutes",
    participantsCount: 1,
    guidelines: [
      "Duration – 5 minutes",
      "Participant – 1",
    ],
  },
  {
    id: "mimicry",
    name: "Mimicry",
    stageType: "on-stage",
    category: "Theatre",
    type: "solo",
    gender: "open",
    duration: "5 minutes",
    participantsCount: 1,
    guidelines: [
      "Duration – 5 minutes",
      "Participant – 1",
    ],
  },
  {
    id: "debate",
    name: "Debate",
    stageType: "off-stage",
    category: "Literary & Oratory",
    type: "group",
    gender: "open",
    duration: "4-5 minutes",
    participantsCount: 2,
    guidelines: [
      "Duration: 4–5 minutes",
      "Participants: Each department shall be represented by one team consisting of two participants",
      "Language: English and Malayalam will be conducted as separate competitions",
      "Topic provided at venue on the spot",
      "One speaks in favour, one speaks against",
      "Judged on content, clarity, presentation, relevance, confidence, and skills",
    ],
  },
  {
    id: "quiz",
    name: "Quiz",
    stageType: "off-stage",
    category: "Literary & Oratory",
    type: "group",
    gender: "open",
    participantsCount: 2,
    guidelines: [
      "Team: 2 participants",
      "Questions will be based on General Knowledge & Current Affairs",
      "Multiple rounds; no electronic devices allowed",
      "Quizmaster's decision is final",
    ],
  },
  {
    id: "aksharashloka",
    name: "Aksharashloka",
    stageType: "off-stage",
    category: "Literary & Oratory",
    type: "solo",
    gender: "open",
    participantsCount: 1,
    guidelines: [
      "Individual participation",
      "Repetition of previously recited verses is not allowed",
      "Time limit as decided by the organisers",
    ],
  },
  {
    id: "kavyakeli",
    name: "Kavyakeli",
    stageType: "off-stage",
    category: "Literary & Oratory",
    type: "solo",
    gender: "open",
    participantsCount: 1,
    guidelines: [
      "Individual participation",
      "Performance must be completed within allotted time",
      "No prompting or external assistance allowed",
    ],
  },
  {
    id: "just-a-minute",
    name: "Just A Minute (JAM)",
    stageType: "off-stage",
    category: "Literary & Oratory",
    type: "solo",
    gender: "open",
    duration: "1 minute",
    participantsCount: 1,
    guidelines: [
      "Individual participation",
      "Language: English",
      "Topic given on the spot",
      "Speak continuously for one minute without repetition, hesitation, or deviation",
    ],
  },
  {
    id: "essay-writing",
    name: "Essay Writing",
    stageType: "off-stage",
    category: "Literary & Oratory",
    type: "solo",
    gender: "open",
    duration: "2 hours",
    participantsCount: 1,
    guidelines: [
      "Individual participation",
      "Time limit: 2 hours",
      "Topic given 10 minutes before competition",
      "Writing materials provided by the Union",
    ],
  },
  {
    id: "short-story-writing",
    name: "Short Story Writing",
    stageType: "off-stage",
    category: "Literary & Oratory",
    type: "solo",
    gender: "open",
    duration: "2 hours",
    participantsCount: 1,
    guidelines: [
      "Individual participation",
      "Time limit: 2 hours",
      "Topic given 10 minutes before competition",
      "Story must be original and written on the spot",
      "Writing materials provided by the Union",
    ],
  },
  {
    id: "poetry-writing",
    name: "Poetry Writing",
    stageType: "off-stage",
    category: "Literary & Oratory",
    type: "solo",
    gender: "open",
    duration: "2 hours",
    participantsCount: 1,
    guidelines: [
      "Individual participation",
      "Time limit: 2 hours",
      "Topic given 10 minutes before competition",
      "Original work only; materials provided by Union",
    ],
  },
  {
    id: "speech-competition",
    name: "Speech Competition",
    stageType: "off-stage",
    category: "Literary & Oratory",
    type: "solo",
    gender: "open",
    duration: "5 minutes",
    participantsCount: 1,
    guidelines: [
      "Individual participation",
      "Time limit: 5 minutes",
      "Topic given 5 minutes before competition",
      "Speech delivered on the spot without external assistance",
    ],
  },
  {
    id: "rangoli",
    name: "Rangoli",
    stageType: "off-stage",
    category: "Fine Arts & Visual Arts",
    type: "solo",
    gender: "open",
    duration: "2.5 hours",
    participantsCount: 1,
    guidelines: [
      "Individual participation",
      "Maximum Duration: 2.5 hours",
      "Participants must bring all required colour powder and tools themselves",
      "Adhesive materials strictly prohibited",
    ],
  },
  {
    id: "wall-painting",
    name: "Wall Painting",
    stageType: "off-stage",
    category: "Fine Arts & Visual Arts",
    type: "group",
    gender: "open",
    duration: "2 hours",
    participantsCount: 2,
    guidelines: [
      "Team participation – 2 members per team",
      "Maximum duration: 2 hours",
      "Wall and painting area allotted by organisers",
      "Only colour paints allowed; design created on the spot based on given theme",
      "Pre-drawn designs or stencils strictly not allowed",
    ],
  },
  {
    id: "water-colour-painting",
    name: "Water Colour Painting",
    stageType: "off-stage",
    category: "Fine Arts & Visual Arts",
    type: "solo",
    gender: "open",
    duration: "2 hours",
    participantsCount: 1,
    guidelines: [
      "Individual participation",
      "Time limit: 2 hours",
      "Paper provided by Union; bring watercolour materials and tools",
      "Topic given 5 minutes before competition",
    ],
  },
  {
    id: "oil-colour-painting",
    name: "Oil Colour Painting",
    stageType: "off-stage",
    category: "Fine Arts & Visual Arts",
    type: "solo",
    gender: "open",
    duration: "3 hours",
    participantsCount: 1,
    guidelines: [
      "Individual participation",
      "Time limit: 3 hours",
      "Paper provided by Union; bring oil colours and painting tools",
      "Topic given 5 minutes before competition",
    ],
  },
  {
    id: "cartoon-drawing",
    name: "Cartoon Drawing",
    stageType: "off-stage",
    category: "Fine Arts & Visual Arts",
    type: "solo",
    gender: "open",
    duration: "1 hour",
    participantsCount: 1,
    guidelines: [
      "Individual participation",
      "Time limit: 1 hour",
      "Paper provided by Union; bring drawing tools",
      "Topic given 10 minutes before competition",
    ],
  },
  {
    id: "pencil-drawing",
    name: "Pencil Drawing",
    stageType: "off-stage",
    category: "Fine Arts & Visual Arts",
    type: "solo",
    gender: "open",
    duration: "2 hours",
    participantsCount: 1,
    guidelines: [
      "Individual participation",
      "Time limit: 2 hours",
      "Paper provided by Union; bring drawing tools",
      "Only pencil drawing allowed",
      "Topic given 10 minutes before competition",
    ],
  },
  {
    id: "clay-modelling",
    name: "Clay Modelling",
    stageType: "off-stage",
    category: "Fine Arts & Visual Arts",
    type: "solo",
    gender: "open",
    duration: "3 hours",
    participantsCount: 1,
    guidelines: [
      "Individual participation",
      "Time limit: 3 hours",
      "Clay provided by Union; bring brushes and tools",
      "Topic given 10 minutes before competition",
    ],
  },
  {
    id: "embroidery",
    name: "Embroidery",
    stageType: "off-stage",
    category: "Fine Arts & Visual Arts",
    type: "solo",
    gender: "open",
    duration: "2 hours",
    participantsCount: 1,
    guidelines: [
      "Duration: 2 hours",
      "Cloth provided by organisers; bring embroidery materials and tools",
      "Reference picture provided at the spot",
    ],
  },
  {
    id: "poster-making",
    name: "Poster Making",
    stageType: "off-stage",
    category: "Fine Arts & Visual Arts",
    type: "solo",
    gender: "open",
    duration: "2.5 hours",
    participantsCount: 1,
    guidelines: [
      "Individual participation",
      "Time limit: 2.5 hours",
      "Paper provided by Union; bring drawing/colouring materials",
      "Topic given 10 minutes before competition",
    ],
  },
  {
    id: "spot-photography",
    name: "Spot Photography",
    stageType: "off-stage",
    category: "Fine Arts & Visual Arts",
    type: "solo",
    gender: "open",
    duration: "2-2.5 hours",
    participantsCount: 1,
    guidelines: [
      "Individual participation",
      "Duration: 2–2.5 hours",
      "Mobile phone photography only; bring own phone",
      "No editing or filters allowed",
      "Theme/topic given on the spot",
    ],
  },
  {
    id: "face-painting",
    name: "Face Painting",
    stageType: "off-stage",
    category: "Fine Arts & Visual Arts",
    type: "group",
    gender: "open",
    duration: "1.5 hours",
    participantsCount: "1 participant + 1 assistant",
    guidelines: [
      "1 participant + 1 assistant (model)",
      "Time limit: 1.5 hours",
      "Bring all required skin-safe materials",
      "Theme/reference provided at the spot",
    ],
  },
  {
    id: "mehendi",
    name: "Mehendi",
    stageType: "off-stage",
    category: "Fine Arts & Visual Arts",
    type: "solo",
    gender: "open",
    duration: "1.5 hours",
    participantsCount: 1,
    guidelines: [
      "Duration: 1.5 hours",
      "Mehendi provided by organisers",
      "Hand prints, moulds, and reference designs are strictly not allowed",
      "Design must extend at least 6 inches onto the forearm",
    ],
  },
  {
    id: "collage-making",
    name: "Collage Making",
    stageType: "off-stage",
    category: "Fine Arts & Visual Arts",
    type: "solo",
    gender: "open",
    duration: "2 hours",
    participantsCount: 1,
    guidelines: [
      "Individual participation",
      "Time limit: 2 hours",
      "Bring scissors, glue, paper cuttings, and required materials",
      "Topic given on the spot",
    ],
  },
];
